import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/components/common/ReduxProvider';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import AuthProvider from '../components/common/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Js Starter',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ReduxProvider>
          <body className={inter.className}>
            <ThemeRegistry>{children}</ThemeRegistry>
          </body>
        </ReduxProvider>
      </AuthProvider>
    </html>
  );
}
